name: Parsing Tests

on:
  workflow_call:
    inputs:
      uhdm_tests_branch:
        description: 'UHDM-integration-tests branch or URL'
        required: false
        type: 'string'
        default: ''
      plugins_branch:
        description: 'yosys-f4pga-plugins branch or URL'
        required: false
        type: 'string'
        default: ''

env:
  GHA_CUSTOM_LINE_PREFIX: "▌"
  TESTS_TO_SKIP: ibex swerv synthesis opentitan serv serv-minimal hello-uvm assignment-pattern Forever BitsCallOnType OneClass
    Continue AnonymousUnion ParameterUnpackedArray VoidFunction2Returns PatternStruct ImportedFunctionCallInModuleAndSubmodule
    VoidFunctionWithoutReturn cmake PutC OneThis CastInFunctionInGenBlock PatternType FunctionOutputArgument GetC ForkJoinTypes
    EnumFirstInInitial ImportFunction DpiChandle Disable EnumFirst TypedefOnFileLevel UnsizedConstantsParameterParsing Fork
    PatternInFunction TypedefVariableDimensions ParameterUnpackedLogicArray SelectFromUnpackedInFunction PatternReplication
    VoidFunction MultiplePrints BitSelectPartSelectInFunction ImportPackageWithFunction ParameterPackedArray StringAssignment
    SystemFunctions ParameterDoubleUnderscoreInSvFrontend OutputSizeWithParameterOfInstanceInitializedByStructMember
    ParameterOfSizeOfParametrizedPort ParameterOfSizeOfParametrizedPortInSubmodule ParameterOfSizeOfPort StringAssignConcatenation
    StringLocalParamInitByConcatenation StringWithBackslash FunctionWithOverriddenParameter RealValue BitsCallOnParametetrizedTypeFromPackage
    AssignToUnpackedUnionFieldAndReadOtherField IndexedPartSelectInFor NestedPatternPassedAsPort StreamOp
    NestedStructArrayParameterInitializedByPatternPassedAsPort PartSelectInFor SelfSelectsInBitSelectAfterBitSelect
    StructArrayParameterInitializedByPatternPassedAsPort SelectGivenBySelectOnParameterInFunction StreamOperatorBitReverseFunction black-parrot
    bsg

jobs:
  tests-read-uhdm:
    name: Surelog
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      CC: gcc-9
      CXX: g++-9
      GIT_HTTP_LOW_SPEED_LIMIT: 1
      GIT_HTTP_LOW_SPEED_TIME: 600
      DEBIAN_FRONTEND: noninteractive
      GHA_MACHINE_TYPE: "n2-standard-2"
      PARSER: surelog

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update -qq
          sudo apt install -y gcc-9 g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev git libunwind-dev
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

      - name: Checkout submodules
        run: |
          git submodule update --depth 1 --init --recursive \
              Surelog \
              UHDM-integration-tests \
              ;

      - name: Override submodule revisions (if requested)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.uhdm_tests_branch != ''}}
        env:
          UHDM_TESTS_BRANCH_SPEC: ${{github.event.inputs.uhdm_tests_branch}}
        run: |
          source ./.github/scripts/submodule-revision-override.inc.bash

          override-submodule-if-requested \
              'UHDM-integration-tests' \
              "$uhdm_tests_default_gh_user" "$uhdm_tests_default_gh_repo" \
              "$UHDM_TESTS_BRANCH_SPEC"

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries

      # See https://github.com/actions/upload-artifact/issues/38
      - name: Extract
        run: tar -xf binaries.tar

      - name: Build & Test (yosys)
        run: |
          ./.github/scripts/run_group_test.sh

        env:
          TARGET: uhdm/yosys/test-ast

      - name: Rename test results
        if: ${{ always() }}
        run: |
          mv test-results/test-results.passed test-results/test-results-uhdm.passed || true
          mv test-results/test-results.failed test-results/test-results-uhdm.failed || true

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-results
          path: test-results

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: tests-vcddiff-artifacts
          path: UHDM-integration-tests/artifacts

      - name: Upload load graphs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: plots
          path: |
            **/plot_*.svg

  tests-read-systemverilog:
    name: SystemVerilog Plugin
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      CC: gcc-9
      CXX: g++-9
      GIT_HTTP_LOW_SPEED_LIMIT: 1
      GIT_HTTP_LOW_SPEED_TIME: 600
      DEBIAN_FRONTEND: noninteractive
      GHA_MACHINE_TYPE: "n2-standard-2"
      PARSER: yosys-plugin

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update -qq
          sudo apt install -y gcc-9 g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev git libunwind-dev
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

      - name: Checkout submodules
        run: |
          git submodule update --depth 1 --init --recursive \
              Surelog \
              UHDM-integration-tests \
              ;

      - name: Override submodule revisions (if requested)
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.uhdm_tests_branch != ''}}
        env:
          UHDM_TESTS_BRANCH_SPEC: ${{github.event.inputs.uhdm_tests_branch}}
        run: |
          source ./.github/scripts/submodule-revision-override.inc.bash

          override-submodule-if-requested \
              'UHDM-integration-tests' \
              "$uhdm_tests_default_gh_user" "$uhdm_tests_default_gh_repo" \
              "$UHDM_TESTS_BRANCH_SPEC"

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries

      # See https://github.com/actions/upload-artifact/issues/38
      - name: Extract
        run: tar -xf binaries.tar

      - name: Build & Test (yosys)
        run: |
          ./.github/scripts/run_group_test.sh
          git diff

        env:
          TARGET: uhdm/yosys/test-ast

      - name: Rename test results
        if: ${{ always() }}
        run: |
          mv test-results/test-results.passed test-results/test-results-systemverilog.passed || true
          mv test-results/test-results.failed test-results/test-results-systemverilog.failed || true

      - name: Push branch
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          source ./.github/scripts/submodule-revision-override.inc.bash
          gh_user="$yosys_f4pga_plugins_default_gh_user"
          gh_repo="$yosys_f4pga_plugins_default_gh_repo"
          branch_spec="$PLUGINS_BRANCH_SPEC"
          gh_branch="$branch_spec"
          parse-custom-branch-spec gh_user gh_repo gh_branch "$branch_spec"
          gh_rev="$(git ls-remote -q "$gh_repo_url" "$gh_branch" 2>/dev/null | head -n1 | cut -f 1)"
          if [[ -z "$gh_rev" && "$gh_branch" =~ ^[0-9a-fA-F]{40}$ ]]; then
            gh_rev="$gh_branch"
            gh_branch=''
          fi
          echo "yosys-f4pga-plugins: $gh_user -> $gh_repo -> $PLUGINS_BRANCH_SPEC -> $gh_rev"
          echo "UHDM-integration-tests: $uhdm_tests_default_gh_user -> $uhdm_tests_default_gh_repo -> $UHDM_TESTS_BRANCH_SPEC"
        env:
          PLUGINS_BRANCH_SPEC: ${{github.event.inputs.plugins_branch}}
          UHDM_TESTS_BRANCH_SPEC: ${{github.event.inputs.uhdm_tests_branch}}

      - name: Push logs
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'logs'
          destination-github-username: 'kamilrakoczy'
          destination-repository-name: 'yosys-systemverilog-logs'
          commit-message: 'Update logs'
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          target-branch: main

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-results
          path: test-results

      - name: Upload load graphs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: plots
          path: |
            **/plot_*.svg

  generate-tests-summary:
    name: Summary Generation
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs:
      - tests-read-uhdm
      - tests-read-systemverilog

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download test results
        uses: /actions/download-artifact@v3
        with:
          name: test-results

      - name: Generate summary
        run: |
          ./.github/scripts/generate_summary.sh
